version: '3'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7
    ports:
      - "5672:5672"  # Bindiamos el puerto dado que es útil para depurar.
      - "15672:15672"  # Este puerto nos permite entrar al panel de monitorización
    environment:
      - RABBITMQ_DEFAULT_USER = conejo
      - RABBITMQ_DEFAULT_PASS = conejosecreto
  worker:
    build: .
    command: bash -c "sleep 10 && celery -A ejemplo_celery worker --loglevel=info"
    volumes:
      - .:/code
    links:
      - rabbit
    environment:
      - RABBIT_HOST=rabbit
      - RABBITMQ_DEFAULT_USER = conejo
      - RABBITMQ_DEFAULT_PASS = conejosecreto
    depends_on:
      - rabbit
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - RABBIT_HOST=rabbit
      - RABBITMQ_DEFAULT_USER = conejo
      - RABBITMQ_DEFAULT_PASS = conejosecreto
    depends_on:
      - rabbit
      - worker