version: '3'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    ports:
      - "5672:5672"  # Bindiamos el puerto dado que es útil para depurar.
      - "15672:15672"  # Este puerto nos permite entrar al panel de monitorización
  worker:
    build: .
    command: bash -c "sleep 10 && celery -A ejemplo_celery worker --loglevel=info"
    volumes:
      - .:/code
    links:
      - rabbit
    environment:
      - RABBIT_HOST=rabbit
    depends_on:
      - rabbit
  flower:  
    image: mher/flower
    command: ["flower", "--broker=amqp://guest:guest@rabbit//", "--port=8888"]  
    ports:  
      - 8888:8888  
    depends_on:
      - worker
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - RABBIT_HOST=rabbit
    depends_on:
      - rabbit
      - worker