version: '3'

services:
  redis:
    hostname: redis
    image: redis:latest
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    ports:
      - "5672:5672"  # Bindiamos el puerto dado que es útil para depurar.
      - "15672:15672"  # Este puerto nos permite entrar al panel de monitorización
  worker:
    build: .
    command: bash -c "sleep 10 && celery -A ejemplo_celery worker --loglevel=info"
    volumes:
      - .:/code
    links:
      - rabbit
    environment:
      - RABBIT_HOST=rabbit
      - REDIS_HOST=redis
    depends_on:
      - rabbit
      - redis
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - RABBIT_HOST=rabbit
      - REDIS_HOST=redis
    depends_on:
      - rabbit
      - worker
      - redis